#!/bin/sh

am_version=$(automake --version | head -n1 | cut -d ' ' -f 4)
if test "$am_version" \< "1.9.5b" ; then
    topdir="$(cd `dirname $0` && pwd)"

    echo "WARNING: automake < 1.9.5b doesn't know how to handle relative"
    echo "m4_include paths. Working around it."
    echo
    set -x
    mkdir -p "$topdir/m4/m4"
    ln -sf $topdir/m4/fixups.m4 $topdir/m4/m4/fixups.m4
    set +x
    echo
fi

autoreconf --force --verbose --install -I m4 -I thirdparty/m4
