# The Vision Workbench installation prefix (/usr/local by default)
VWPREFIX = /usr/local

# If you don't have libtool installed, you can specify the full 
# path to the libtool script in the base directory of your Vision 
# Workbench source tree, e.g. $(HOME)/VisionWorkbench-1.0/libtool
LIBTOOL = libtool

# Compilation flags:
# -O3   turns on optimization, which you should almost always do
# -g    enables debugging support
# -Wall turns on all compiler warnings
CXXFLAGS = -I$(VWPREFIX)/include -O3 -g -Wall

# Boost:
# The Vision Workbench header files require the boost headers. If
# boost is installed in a non-standord location, you may need
# to uncomment this line and insert the path to the boost headers.
# CXXFLAGS += -I<path to boost include dir>

# Linking flags:
# -lvw includes the Vision Workbench core libraries
LDFLAGS = -L$(VWPREFIX)/lib -lvw

# Object files:
# List the object files needed to build your program here.
OBJECTS = vwconvert.o

# Linking rule:
# Duplicate and modify this rule to build multiple programs.
vwconvert: $(OBJECTS)
	$(LIBTOOL) --mode=link $(CXX) $(LDFLAGS) -o $@ $^ 

# Clean-up rule:
clean:
	rm -f *.o *~ \#*
