template class  vw::ApplyPixelMask<PixelT>;
template class  vw::ApproximateTransform<TransformT>;
template struct vw::BicubicInterpolation::Interpolator<ViewT>;
template struct vw::BicubicInterpolationImpl<ViewT, PixelT>;
template struct vw::BilinearInterpolation::Interpolator<ViewT>;
template struct vw::BilinearInterpolationImpl<ViewT, PixelT>;
template class  vw::BinaryCompoundFunctor<FuncT, vw::PixelMask<ChildPixel1T>, vw::PixelMask<ChildPixel2T> >;
template class  vw::BinaryInPlaceCompoundFunctor<FuncT, vw::PixelMask<ChildPixel1T>, vw::PixelMask<ChildPixel2T> >;
template class  vw::BinaryPerPixelAccessor<Image1IterT, Image2IterT, FuncT>;
template class  vw::BinaryPerPixelView<Image1T, Image2T, FuncT>;
template class  vw::BlockCacheView<PixelT>;
template class  vw::BlockProcessor<FuncT>;
template class  vw::BlockRasterizeView<ImageT>;
template class  vw::ChannelAccumulator<AccumT>;
template class  vw::ChannelCastClampFunctor<DestT>;
template class  vw::ChannelCastFunctor<DestT>;
template class  vw::ChannelCastRescaleFunctor<DestT>;
template class  vw::ChannelCastRoundClampFunctor<DestT>;
template class  vw::ChannelCastRoundFunctor<DestT>;
template class  vw::ChannelClampFunctor<PixelT>;
template class  vw::ChannelNormalizeFunctor<PixelT>;
template class  vw::ChannelNormalizeRetainAlphaFunctor<PixelT>;
template struct vw::ChannelRange<T>;
//template struct vw::ChannelRangeHelper<T, <anonymous> >;
template struct vw::ChannelRangeHelper<T, false>;
template class  vw::ChannelThresholdFunctor<PixelT>;
template struct vw::ChannelTypeID<ChannelT>;
template class  vw::ChannelsToPlanesAccessor<ChildT>;
template class  vw::ChannelsToPlanesView<ImageT>;
template class  vw::CompositionTransform<Tx1T, Tx2T>;
template struct vw::CompoundChannelCast<vw::PixelGray<ChT>, NewChT>;
template struct vw::CompoundChannelCast<vw::PixelGray<ChT>, const NewChT>;
template struct vw::CompoundChannelCast<vw::PixelGrayA<ChT>, NewChT>;
template struct vw::CompoundChannelCast<vw::PixelGrayA<ChT>, const NewChT>;
template struct vw::CompoundChannelCast<vw::PixelHSV<ChT>, NewChT>;
template struct vw::CompoundChannelCast<vw::PixelHSV<ChT>, const NewChT>;
template struct vw::CompoundChannelCast<vw::PixelLab<ChT>, NewChT>;
template struct vw::CompoundChannelCast<vw::PixelLab<ChT>, const NewChT>;
template struct vw::CompoundChannelCast<vw::PixelLuv<ChT>, NewChT>;
template struct vw::CompoundChannelCast<vw::PixelLuv<ChT>, const NewChT>;
template struct vw::CompoundChannelCast<vw::PixelMask<ChildT>, NewChT>;
template struct vw::CompoundChannelCast<vw::PixelMask<ChildT>, const NewChT>;
template struct vw::CompoundChannelCast<vw::PixelRGB<ChT>, NewChT>;
template struct vw::CompoundChannelCast<vw::PixelRGB<ChT>, const NewChT>;
template struct vw::CompoundChannelCast<vw::PixelRGBA<ChT>, NewChT>;
template struct vw::CompoundChannelCast<vw::PixelRGBA<ChT>, const NewChT>;
template struct vw::CompoundChannelCast<vw::PixelXYZ<ChT>, NewChT>;
template struct vw::CompoundChannelCast<vw::PixelXYZ<ChT>, const NewChT>;
template struct vw::CompoundChannelCast<vw::math::Vector<OldChT, SizeN>, NewChT>;
template struct vw::CompoundChannelCast<vw::math::Vector<OldChT, SizeN>, const NewChT>;
template class  vw::ConstantView<PixelT>;
template class  vw::ConvolutionView<ImageT, KernelT, EdgeT>;
template class  vw::CopyPixelMask<PixelT>;
template class  vw::CopyView<ImageT>;
template class  vw::CreatePixelMask<PixelT>;
template class  vw::CropView<ImageT>;
template struct vw::DefaultKernelT<PixelT>;
template struct vw::EdgeExtensionBase::result<ArgsT>;
template class  vw::EdgeExtensionView<ImageT, ExtensionT>;
template class  vw::FlipHorizontalPixelAccessor<ChildT>;
template class  vw::FlipHorizontalView<ImageT>;
template class  vw::FlipVerticalPixelAccessor<ChildT>;
template class  vw::FlipVerticalView<ImageT>;
template class  vw::ImageResourceView<PixelT>;
template class  vw::ImageView<PixelT>;
template struct vw::ImageViewBase<ImageT>;
template class  vw::ImageViewRef<PixelT>;
//template class  vw::ImageViewRefAccessor<PixelT>;
template class  vw::ImageViewRefAccessorBase<PixelT>;
template class  vw::ImageViewRefAccessorImpl<IterT>;
template class  vw::ImageViewRefBase<PixelT>;
template class  vw::ImageViewRefImpl<ViewT>;
template struct vw::InterpolationBase::result<ArgsT>;
template class  vw::InterpolationView<ImageT, InterpT>;
template class  vw::InverseTransform<TxT>;
template struct vw::IsFloatingPointIndexable<ImplT>;
template struct vw::IsImageView<ImageT>;
template struct vw::IsMultiplyAccessible<ImplT>;
template struct vw::IsResizable<ImplT>;
//template class  vw::MaskToAlpha<PixelT>;
template struct vw::MaskedPixelType<PixelT>;
template class  vw::MemoryStridingPixelAccessor<PixelT>;
template struct vw::NearestPixelInterpolation::Interpolator<ViewT>;
template class  vw::PaletteFilter<PixelT>;
template class  vw::PixelAccumulator<AccumT>;
template struct vw::PixelCastFunctor<PixelT>;
template struct vw::PixelCastRescaleFunctor<PixelT>;
template struct vw::PixelChannelCast<T, ChannelT>;
template struct vw::PixelChannelCastFunctor<ChannelT>;
template struct vw::PixelChannelCastRescaleFunctor<ChannelT>;
template struct vw::PixelChannelType<T>;
template struct vw::PixelFormatID<PixelT>;
template class  vw::PixelGray<ChannelT>;
template class  vw::PixelGrayA<ChannelT>;
template class  vw::PixelHSV<ChannelT>;
template struct vw::PixelHasAlpha<T>;
//template class  vw::PixelIterator<ViewT>;
template class  vw::PixelLab<ChannelT>;
template class  vw::PixelLuv<ChannelT>;
template struct vw::PixelMakeComplex<PixelT>;
template struct vw::PixelMakeReal<PixelT>;
//template struct vw::PixelMask<ChildT>;
template class  vw::PixelMathBase<DerivedT>;
template struct vw::PixelNumChannels<T>;
template class  vw::PixelRGB<ChannelT>;
template class  vw::PixelRGBA<ChannelT>;
template struct vw::PixelTypeFromPixelAccessor<PixelAccessorT>;
template struct vw::PixelWithAlpha<T>;
template struct vw::PixelWithoutAlpha<T>;
template class  vw::PixelXYZ<ChannelT>;
//template class  vw::PlanesToChannelsView<PixelT, ImageT>;
template class  vw::ProceduralPixelAccessor<ViewT>;
template class  vw::RadialTransformAdaptor<ImplT, ImageT>;
template class  vw::Rotate180PixelAccessor<ChildT>;
template class  vw::Rotate180View<ImageT>;
template class  vw::Rotate90CCWPixelAccessor<ChildT>;
template class  vw::Rotate90CCWView<ImageT>;
template class  vw::Rotate90CWPixelAccessor<ChildT>;
template class  vw::Rotate90CWView<ImageT>;
template struct vw::SelectChannelFunctor<ImageT>;
template class  vw::SelectColView<ImageT>;
template class  vw::SelectPlaneView<ImageT>;
template class  vw::SelectRowView<ImageT>;
//template class  vw::SeparableConvolutionView<ImageT, KernelT, EdgeT>;
template class  vw::SubsamplePixelAccessor<ChildT>;
template class  vw::SubsampleView<ImageT>;
template class  vw::ThreadedBlockWriter::RasterizeBlockTask<ViewT>;
template class  vw::ThreadedBlockWriter::WriteBlockTask<PixelT>;
template class  vw::TransformBase<ImplT>;
template class  vw::TransformHelper<ImplT, ForwardType, ReverseType>;
template class  vw::TransformView<ImageT, TransformT>;
template class  vw::TransposePixelAccessor<ChildT>;
template class  vw::TransposeView<ImageT>;
template class  vw::TrinaryPerPixelAccessor<Image1IterT, Image2IterT, Image3IterT, FuncT>;
template class  vw::TrinaryPerPixelView<Image1T, Image2T, Image3T, FuncT>;
template class  vw::UnaryCompoundFunctor<FuncT, vw::PixelMask<ChildPixel1T> >;
template class  vw::UnaryInPlaceCompoundFunctor<FuncT, vw::PixelMask<ChildPixel1T> >;
template class  vw::UnaryPerPixelAccessor<ImageIterT, FuncT>;
template class  vw::UnaryPerPixelAccessorView<ImageT, FuncT>;
template class  vw::UnaryPerPixelView<ImageT, FuncT>;
template struct vw::UnmaskedPixelType<PixelT>;
template struct vw::ValueEdgeExtension<PixelT>;
template class  vw::ViewImageResource<ViewT>;
template struct vw::WeightedRGBToGrayFunctor::result<ArgsT>;
