// __BEGIN_LICENSE__
// Copyright (C) 2006-2010 United States Government as represented by
// the Administrator of the National Aeronautics and Space Administration.
// All Rights Reserved.
// __END_LICENSE__


void main(in float2 texCoord0 : TEXCOORD0,
        uniform samplerRECT i1,
        out float4 color : COLOR )
{
   float4 value = texRECT(i1, texCoord0);
   color = 0.5 * log((value + 1.0) / (value - 1.0));
}