// __BEGIN_LICENSE__
// Copyright (C) 2006-2010 United States Government as represented by
// the Administrator of the National Aeronautics and Space Administration.
// All Rights Reserved.
// __END_LICENSE__


void main(in float2 texCoord0 : TEXCOORD0,
        uniform samplerRECT i1,
        uniform float f1,
        out float4 color : COLOR )
{
   color = sqrt(float4(pow(f1, 2.0)) + pow(texRECT(i1, texCoord0), float4(2.0)));
}