// __BEGIN_LICENSE__
// Copyright (C) 2006-2010 United States Government as represented by
// the Administrator of the National Aeronautics and Space Administration.
// All Rights Reserved.
// __END_LICENSE__


void main(in float2 texCoord0 : TEXCOORD0,
        uniform samplerRECT i1,
        uniform samplerRECT i2,
        out float4 color : COLOR )
{
   color = texRECT(i1, texCoord0) * texRECT(i2, texCoord0);
}