template struct vw::AccumulatorType<T>;
template struct vw::ArgValDifferenceFunctor<ValT>;
template struct vw::ArgValEqualityFunctor<ValT>;
template struct vw::ArgValGreaterThanFunctor<ValT>;
template struct vw::ArgValGreaterThanOrEqualFunctor<ValT>;
template struct vw::ArgValInPlaceDifferenceFunctor<ValT>;
template struct vw::ArgValInPlaceProductFunctor<ValT>;
template struct vw::ArgValInPlaceQuotientFunctor<ValT>;
template struct vw::ArgValInPlaceSafeQuotientFunctor<ValT>;
template struct vw::ArgValInPlaceSumFunctor<ValT>;
template struct vw::ArgValInequalityFunctor<ValT>;
template struct vw::ArgValLessThanFunctor<ValT>;
template struct vw::ArgValLessThanOrEqualFunctor<ValT>;
template struct vw::ArgValProductFunctor<ValT>;
template struct vw::ArgValQuotientFunctor<ValT>;
template struct vw::ArgValSafeQuotientFunctor<ValT>;
template struct vw::ArgValSumFunctor<ValT>;
template class  vw::BinaryCompoundFunctor<FuncT, FuncArg1T, FuncArg2T>;
template struct vw::BinaryCompoundFunctor<vw::ArgArgProductFunctor, vw::PixelGray<float>, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, Arg1T, Arg2T>;
template struct vw::BinaryCompoundFunctor<vw::ArgArgProductFunctor, vw::PixelGray<float>, vw::PixelGray<float> >::result<ArgsT>;
template struct vw::BinaryCompoundFunctor<vw::ArgArgSumFunctor, vw::PixelRGB<int>, vw::PixelRGB<int> >::Helper<CompoundB, ChannelsN, ResultT, Arg1T, Arg2T>;
template struct vw::BinaryCompoundFunctor<vw::ArgArgSumFunctor, vw::PixelRGB<int>, vw::PixelRGB<int> >::result<ArgsT>;
template struct vw::BinaryCompoundFunctor<vw::math::ArgArgAtan2Functor, vw::PixelGray<float>, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, Arg1T, Arg2T>;
template struct vw::BinaryCompoundFunctor<vw::math::ArgArgAtan2Functor, vw::PixelGray<float>, vw::PixelGray<float> >::result<ArgsT>;
template struct vw::BinaryCompoundFunctor<vw::math::ArgArgHypotFunctor, vw::PixelGray<float>, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, Arg1T, Arg2T>;
template struct vw::BinaryCompoundFunctor<vw::math::ArgArgHypotFunctor, vw::PixelGray<float>, vw::PixelGray<float> >::result<ArgsT>;
template class  vw::BinaryInPlaceCompoundFunctor<FuncT, FuncArg1T, FuncArg2T>;
template struct vw::BinaryInPlaceCompoundFunctor<vw::ArgArgInPlaceSumFunctor, vw::PixelGray<float>, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, Arg1T, Arg2T>;
template struct vw::BinaryInPlaceCompoundFunctor<vw::ArgArgInPlaceSumFunctor, vw::PixelGray<float>, vw::PixelGray<float> >::result<ArgsT>;
template struct vw::BinaryInPlaceCompoundFunctor<vw::ArgArgInPlaceSumFunctor, vw::PixelRGB<float>, vw::PixelRGB<float> >::Helper<CompoundB, ChannelsN, Arg1T, Arg2T>;
template struct vw::BinaryInPlaceCompoundFunctor<vw::ArgArgInPlaceSumFunctor, vw::PixelRGB<float>, vw::PixelRGB<float> >::result<ArgsT>;
template struct vw::BinaryReturn1stType::result<Arg1T, Arg2T>;
template struct vw::BinaryReturn2ndType::result<Arg1T, Arg2T>;
template struct vw::BinaryReturnTemplateType<vw::DifferenceType>::result<Args>;
template struct vw::BinaryReturnTemplateType<vw::ProductType>::result<Args>;
template struct vw::BinaryReturnTemplateType<vw::QuotientType>::result<Args>;
template struct vw::BinaryReturnTemplateType<vw::SumType>::result<Args>;
//template struct vw::BinaryReturnTernaryTemplateBind1st<ResultT, ValT>;
template struct vw::BinaryReturnTernaryTemplateBind1st<vw::math::BinaryFunctorType, vw::math::ArgArgAtan2Functor>::result<Args>;
template struct vw::BinaryReturnTernaryTemplateBind1st<vw::math::BinaryFunctorType, vw::math::ArgArgCopysignFunctor>::result<Args>;
template struct vw::BinaryReturnTernaryTemplateBind1st<vw::math::BinaryFunctorType, vw::math::ArgArgFdimFunctor>::result<Args>;
template struct vw::BinaryReturnTernaryTemplateBind1st<vw::math::BinaryFunctorType, vw::math::ArgArgHypotFunctor>::result<Args>;
template struct vw::BinaryReturnTernaryTemplateBind1st<vw::math::BinaryFunctorType, vw::math::ArgArgPowFunctor>::result<Args>;
template class  vw::Cache::CacheLine<GeneratorT>;
template class  vw::Cache::Handle<GeneratorT>;
template struct vw::ClassType<T>;
template struct vw::CompoundAccumulatorType<T>;
template struct vw::CompoundChannelCast<T, ChannelT>;
template struct vw::CompoundChannelCast<const T, ChannelT>;
template struct vw::CompoundChannelType<T>;
template struct vw::CompoundChannelType<const T>;
template struct vw::CompoundIsCompatible<T1, T2>;
template struct vw::CompoundIsCompatible<T1, const T2>;
template struct vw::CompoundNumChannels<T>;
template struct vw::CompoundNumChannels<const T>;
template struct vw::CompoundResult<FuncT, Arg1T, Arg2T>;
template struct vw::CompoundResult<FuncT, ArgT, void>;
template struct vw::CopyCVR<SrcT, DstT>;
template struct vw::DifferenceType<Arg1T, Arg2T>;
template struct vw::DifferenceTypeSpecialization<Arg1T, Arg2T>;
template struct vw::FloatType<T>;
template class  vw::FundamentalTypeClass<T>;
template struct vw::IsCompound<T>;
template struct vw::IsCompound<const T>;
template struct vw::IsScalar<T>;
template struct vw::IsScalar<const T>;
template struct vw::IsScalarOrCompound<T>;
template struct vw::MakeComplex<T>;
template struct vw::MakeReal<T>;
template class  vw::MultiOutputBuf<CharT, traits>;
template class  vw::MultiOutputStream<CharT, traits>;
template class  vw::MultiOutputStreamInit<CharT, traits>;
template class  vw::NullOutputBuf<CharT, traits>;
template class  vw::NullOutputStream<CharT, traits>;
template class  vw::NullOutputStreamInit<CharT, traits>;
template class  vw::PerThreadBufferedStream<CharT, traits>;
template class  vw::PerThreadBufferedStreamBuf<CharT, traits>;
template class  vw::PerThreadBufferedStreamBufInit<CharT, traits>;
template struct vw::ProductType<Arg1T, Arg2T>;
template struct vw::ProductTypeSpecialization<Arg1T, Arg2T>;
template struct vw::PromoteType<Arg1T, Arg2T>;
template class  vw::PromoteTypeSpecialization<Arg1T, Arg2T>;
template struct vw::PromoteTypeSpecializationHelper<Arg1T, Arg2T, Arg1IsCompound, Arg2IsCompound>;
template struct vw::PromoteTypeSpecializationHelper<Arg1T, Arg2T, false, true>;
template struct vw::PromoteTypeSpecializationHelper<Arg1T, Arg2T, true, false>;
template struct vw::PromoteTypeSpecializationHelper<Arg1T, Arg2T, true, true>;
template struct vw::QuotientType<Arg1T, Arg2T>;
template struct vw::QuotientTypeSpecialization<Arg1T, Arg2T>;
template struct vw::ReturnFixedType<T>;
template struct vw::ReturnFixedType<bool>::result<Args>;
template struct vw::ReturnFixedType<const double&>::result<Args>;
template struct vw::ReturnFixedType<float>::result<Args>;
template struct vw::ReturnFixedType<unsigned char>::result<Args>;
template struct vw::ReturnFixedType<void>::result<Args>;
template struct vw::ReturnFixedType<vw::PixelDisparity<float> >::result<Args>;
template struct vw::ReturnFixedType<vw::PixelGray<float> >::result<Args>;
template struct vw::ReturnFixedType<vw::PixelRGB<unsigned char> >::result<Args>;
template struct vw::ScalarTypeLimits<T>;
template struct vw::SumType<Arg1T, Arg2T>;
template struct vw::SumTypeSpecialization<Arg1T, Arg2T>;
template class  vw::Thread::TaskHelper<TaskT>;
//template struct vw::TypeDeductionError<T>;
template struct vw::TypeDeductionHelper<Arg1T, Arg2T>;
template struct vw::TypeDeductionHelper<ArgT, ArgT>;
template struct vw::TypeDeductionHelper<T, double>;
template struct vw::TypeDeductionHelper<T, float>;
template struct vw::TypeDeductionHelper<T, int>;
template struct vw::TypeDeductionHelper<T, long double>;
template struct vw::TypeDeductionHelper<T, long int>;
template struct vw::TypeDeductionHelper<T, long unsigned int>;
template struct vw::TypeDeductionHelper<T, short int>;
template struct vw::TypeDeductionHelper<T, short unsigned int>;
template struct vw::TypeDeductionHelper<T, signed char>;
template struct vw::TypeDeductionHelper<T, unsigned char>;
template struct vw::TypeDeductionHelper<T, unsigned int>;
template struct vw::TypeDeductionHelper<double, T>;
template struct vw::TypeDeductionHelper<float, T>;
template struct vw::TypeDeductionHelper<int, T>;
template struct vw::TypeDeductionHelper<long double, T>;
template struct vw::TypeDeductionHelper<long int, T>;
template struct vw::TypeDeductionHelper<long unsigned int, T>;
template struct vw::TypeDeductionHelper<short int, T>;
template struct vw::TypeDeductionHelper<short unsigned int, T>;
template struct vw::TypeDeductionHelper<signed char, T>;
template struct vw::TypeDeductionHelper<unsigned char, T>;
template struct vw::TypeDeductionHelper<unsigned int, T>;
template class  vw::UnaryCompoundFunctor<FuncT, FuncArgT>;
template struct vw::UnaryCompoundFunctor<vw::ArgNegationFunctor, vw::PixelGray<double> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ArgNegationFunctor, vw::PixelGray<double> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValDifferenceFunctor<double>, vw::PixelGray<double> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValDifferenceFunctor<double>, vw::PixelGray<double> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValProductFunctor<float>, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValProductFunctor<float>, vw::PixelGray<float> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValProductFunctor<vw::PixelGray<float> >, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValProductFunctor<vw::PixelGray<float> >, vw::PixelGray<float> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValQuotientFunctor<double>, vw::PixelGray<double> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValQuotientFunctor<double>, vw::PixelGray<double> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValQuotientFunctor<int>, vw::PixelRGB<int> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValQuotientFunctor<int>, vw::PixelRGB<int> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValQuotientFunctor<int>, vw::PixelRGB<unsigned char> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValQuotientFunctor<int>, vw::PixelRGB<unsigned char> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValSumFunctor<vw::PixelRGB<int> >, vw::PixelRGB<int> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ArgValSumFunctor<vw::PixelRGB<int> >, vw::PixelRGB<int> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ChannelCastFunctor<float>, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ChannelCastFunctor<float>, vw::PixelGray<float> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ChannelCastRescaleFunctor<float>, vw::PixelRGB<unsigned char> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ChannelCastRescaleFunctor<float>, vw::PixelRGB<unsigned char> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ChannelCastRescaleFunctor<unsigned char>, vw::PixelRGB<unsigned char> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ChannelCastRescaleFunctor<unsigned char>, vw::PixelRGB<unsigned char> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ValArgProductFunctor<float>, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ValArgProductFunctor<float>, vw::PixelGray<float> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ValArgProductFunctor<float>, vw::PixelRGB<unsigned char> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ValArgProductFunctor<float>, vw::PixelRGB<unsigned char> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ValArgProductFunctor<vw::PixelGray<float> >, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ValArgProductFunctor<vw::PixelGray<float> >, vw::PixelGray<float> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::ValArgSumFunctor<vw::PixelRGB<int> >, vw::PixelRGB<int> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::ValArgSumFunctor<vw::PixelRGB<int> >, vw::PixelRGB<int> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::math::ArgExpFunctor, vw::PixelGray<double> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::math::ArgExpFunctor, vw::PixelGray<double> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::math::ArgValAtan2Functor<vw::PixelGray<float> >, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::math::ArgValAtan2Functor<vw::PixelGray<float> >, vw::PixelGray<float> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::math::ArgValHypotFunctor<vw::PixelGray<float> >, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::math::ArgValHypotFunctor<vw::PixelGray<float> >, vw::PixelGray<float> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::math::ArgValPowFunctor<int>, vw::PixelGray<double> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::math::ArgValPowFunctor<int>, vw::PixelGray<double> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::math::ValArgAtan2Functor<vw::PixelGray<float> >, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::math::ValArgAtan2Functor<vw::PixelGray<float> >, vw::PixelGray<float> >::result<ArgsT>;
template struct vw::UnaryCompoundFunctor<vw::math::ValArgHypotFunctor<vw::PixelGray<float> >, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ResultT, ArgT>;
template struct vw::UnaryCompoundFunctor<vw::math::ValArgHypotFunctor<vw::PixelGray<float> >, vw::PixelGray<float> >::result<ArgsT>;
template class  vw::UnaryInPlaceCompoundFunctor<FuncT, FuncArgT>;
template struct vw::UnaryInPlaceCompoundFunctor<const vw::ArgValInPlaceProductFunctor<float>&, vw::PixelGray<float> >::Helper<CompoundB, ChannelsN, ArgT>;
template struct vw::UnaryInPlaceCompoundFunctor<const vw::ArgValInPlaceProductFunctor<float>&, vw::PixelGray<float> >::result<ArgsT>;
//template struct vw::UnaryReturnBinaryTemplateBind1st<ResultT, ValT>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::ProductType, double>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::ProductType, float>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::ProductType, vw::PixelGray<float> >::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::SumType, vw::PixelRGB<int> >::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgAcosFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgAcoshFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgAsinFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgAsinhFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgAtanFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgAtanhFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgCbrtFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgCeilFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgCosFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgCoshFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgErfFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgErfcFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgExp2Functor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgExpFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgExpm1Functor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgFabsFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgFloorFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgLgammaFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgLog10Functor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgLog1pFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgLog2Functor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgLogFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgRoundFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgSinFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgSinhFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgSqrtFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgTanFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgTanhFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgTgammaFunctor>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind1st<vw::math::ArgUnaryFunctorType, vw::math::ArgTruncFunctor>::result<Args>;
//template struct vw::UnaryReturnBinaryTemplateBind2nd<ResultT, ValT>;
template struct vw::UnaryReturnBinaryTemplateBind2nd<vw::CompoundChannelCast, float>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind2nd<vw::CompoundChannelCast, unsigned char>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind2nd<vw::DifferenceType, double>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind2nd<vw::ProductType, double>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind2nd<vw::ProductType, float>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind2nd<vw::ProductType, vw::PixelGray<float> >::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind2nd<vw::QuotientType, double>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind2nd<vw::QuotientType, int>::result<Args>;
template struct vw::UnaryReturnBinaryTemplateBind2nd<vw::SumType, vw::PixelRGB<int> >::result<Args>;
//template struct vw::UnaryReturnSameType::result<Args>;
template struct vw::UnaryReturnTemplateType<vw::MakeReal>::result<Args>;
template struct vw::UnaryReturnTemplateType<vw::PixelTypeFromPixelAccessor>::result<Args>;
//template struct vw::UnaryReturnTernaryTemplateBind1st2nd<ResultT, Val1T, Val2T>;
template struct vw::UnaryReturnTernaryTemplateBind1st2nd<vw::math::BinaryFunctorType, vw::math::ArgArgAtan2Functor, vw::PixelGray<float> >::result<Args>;
template struct vw::UnaryReturnTernaryTemplateBind1st2nd<vw::math::BinaryFunctorType, vw::math::ArgArgHypotFunctor, vw::PixelGray<float> >::result<Args>;
//template struct vw::UnaryReturnTernaryTemplateBind1st3rd<ResultT, Val1T, Val3T>;
template struct vw::UnaryReturnTernaryTemplateBind1st3rd<vw::math::BinaryFunctorType, vw::math::ArgArgAtan2Functor, vw::PixelGray<float> >::result<Args>;
template struct vw::UnaryReturnTernaryTemplateBind1st3rd<vw::math::BinaryFunctorType, vw::math::ArgArgHypotFunctor, vw::PixelGray<float> >::result<Args>;
template struct vw::UnaryReturnTernaryTemplateBind1st3rd<vw::math::BinaryFunctorType, vw::math::ArgArgPowFunctor, int>::result<Args>;
template struct vw::ValArgDifferenceFunctor<ValT>;
template struct vw::ValArgEqualityFunctor<ValT>;
template struct vw::ValArgGreaterThanFunctor<ValT>;
template struct vw::ValArgGreaterThanOrEqualFunctor<ValT>;
template struct vw::ValArgInequalityFunctor<ValT>;
template struct vw::ValArgLessThanFunctor<ValT>;
template struct vw::ValArgLessThanOrEqualFunctor<ValT>;
template struct vw::ValArgProductFunctor<ValT>;
template struct vw::ValArgQuotientFunctor<ValT>;
template struct vw::ValArgSafeQuotientFunctor<ValT>;
template struct vw::ValArgSumFunctor<ValT>;
template class  vw::VarArray<T>;
